version: '3.1'
services:
    client:
        image: node:10-alpine
        container_name: client
        working_dir: '/client'
        volumes: 
            - './client/:/client/'
        command: 'npm run start'
        ports:
            - '3000:3000'
        tty: true
        stdin_open: true
